_merge = "deep"

languageCode = 'fr-fr'
title = 'DILA'

[module]
[[module.imports]]
path = 'github.com/disic/frago'

[outputs]
 home    = ["HTML","JSON"]
 page    = ["HTML","JSON","declaration","declarationpage","accessibility","accessibilitypage","quality","qualitypage","performance","performancepage"]

[params]
  organisation = "DILA"
  robots = "noindex, nofollow"
